import {LandCardType} from "../Types/Land/LandCardType";

export const landActionTypes = {
    0: "ADD",
    1: "EDIT",
}

export const categoryOptions = ["Шлак", "Дом", "Землянка"]
export const categoryOptionsValues = ["Shlak", "Home", "Zemlya"]
export const objectOptions = ["Пустырь", "Дом", "Завод", "Гараж"]
export const objectOptionsValues = ["Pystir", "Home", "Zavod", "Garazh"]
export const searchChannelOptions = ["Аукцион", "Сторонний источник", "Тест1"]
export const searchChannelOptionsValues = ["Auction", "Alternative", "Test1"]


export const landsExamples: LandCardType[] = [
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "123=-1231-21231-2",
        landCategory: "1",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTestcadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "categoryTest",
        landId: "adwawdadawd",
        landObject: ["dawda"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
    },
]