import {LandCardType} from "../Types/Land/LandCardType";

export const categoryOptions = ["Шлак", "Дом", "Землянка"]
export const categoryOptionsValues = ["Shlak", "Home", "Zemlya"]
export const objectOptions = ["Пустырь", "Дом", "Завод", "Гараж"]
export const objectOptionsValues = ["Pystir", "Home", "Zavod", "Garazh"]
export const searchChannelOptions = ["Аукцион", "Сторонний источник", "Тест1"]
export const searchChannelOptionsValues = ["Auction", "Alternative", "Test1"]


export const mainInfoTitles = ["Кадастровый номер", "Дата внесения в базу", "Площадь", "Адрес", "Категория",
    "Статус", "Этап", "Канал поиска"]
export const legalInfoTitles = ["Количество объектов", "Количество собственников", "Вид разрешенного использования",
    "Ограничения и обременения", "Кадастровая стоимость"]
export const objectsInfoTitles = ["Объект"]
export const additionalInfoTitles = ["Наличие инженерных сетей", "Наличие транспорта", "Экономика"]
export const copyrightInfoTitles = ["Правообладатель", "Почта", "Телефон"]
export const tasksInfoTitles = ["Завершено"]


export const landsExamples: LandCardType[] = [
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: false,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: true,
    },
    {
        landTitle: "Тест",
        landAddress: "addressTest",
        landCadastrial: "cadastrialTest",
        landCategory: "Zemlya",
        landId: "adwawdadawd",
        landObject: ["Zavod"],
        landSquare: "23",
        landAddingDate: new Date("2023-10-11"),
        landCopyrightHolder: "Kto-to",
        landSearchChannel: "awdawdawd",
        landStatus: "new",
        landArchived: true,
    },
]